# Generated by Django 4.2.26 on 2025-11-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('project_image', models.ImageField(upload_to='', verbose_name='Project Image')),
                ('project_des', models.TextField(verbose_name='Project description')),
                ('features', models.CharField(max_length=200, verbose_name='Features')),
                ('technologies_used', models.TextField(max_length=50, verbose_name='Technologies Used')),
                ('live_demo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
