# Generated by Django 4.2.26 on 2025-12-22 10:05

from django.db import migrations, models
import django.db.models.deletion
import portfolio_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=30, verbose_name='Certification Name')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compony_name', models.CharField(max_length=100, verbose_name='Compony Name')),
                ('compony_des', models.TextField(verbose_name='Description')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('certificate_link', models.URLField(blank=True, null=True, verbose_name='Certificate Link')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100, verbose_name='Project Name')),
                ('project_video', models.FileField(blank=True, null=True, upload_to='portfolio_app/videos', validators=[portfolio_app.models.Project.validator_video], verbose_name='Project Video')),
                ('project_des', models.TextField(verbose_name='Project Description')),
                ('live_demo', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('languages', 'Languages'), ('frameworks', 'Frameworks/Libraries'), ('frontend', 'Frontend Technologies'), ('backend', 'backend Technologies'), ('databases', 'Databases'), ('ml/ds', 'ML/Data Science'), ('cloud', 'Cloud/DevOps'), ('tools', 'Tools')], default='languages', max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='portfolio/icon')),
            ],
        ),
        migrations.CreateModel(
            name='TechUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Technology Used')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='portfolio_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='TechIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='portfolio_app/icon')),
                ('tech_name', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='portfolio_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_app/profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Feature')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='portfolio_app.project')),
            ],
        ),
    ]
