# Generated by Django 4.2.26 on 2025-11-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_icon',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used',
            field=models.CharField(max_length=50, verbose_name='Technologies Used'),
        ),
    ]
