# Generated by Django 4.2.26 on 2025-11-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_project_tech_icon_alter_project_technologies_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='project_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_icon',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies_used',
        ),
        migrations.AddField(
            model_name='project',
            name='project_profile',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_app/profile', verbose_name='Project Profile'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming Languages'), ('frontend', 'Frontend Technologies'), ('backend', 'Backend Technologies'), ('database', 'Databases'), ('framework', 'Frameworks & Libraries'), ('datasci', 'Data Science / Machine Learning'), ('tools', 'Tools & Platforms')], default='programming', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_des',
            field=models.TextField(verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/icon'),
        ),
        migrations.CreateModel(
            name='TechUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Technology Used')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='portfolio_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='TechIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='portfolio_app/icon')),
                ('tech_name', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='portfolio_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Feature')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='portfolio_app.project')),
            ],
        ),
    ]
