# Generated by Django 4.2.26 on 2026-01-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Languages'), ('frameworks', 'Frameworks/Libraries'), ('frontend', 'Frontend Technologies'), ('backend', 'backend Technologies'), ('databases', 'Databases'), ('ml_ds', 'ML/Data Science'), ('cloud', 'Cloud/DevOps'), ('tools', 'Tools')], default='languages', max_length=30),
        ),
    ]
