# Generated by Django 4.2.26 on 2025-11-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_rename_project_name_project_project_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Languages'), ('frameworks', 'Frameworks/Libraries'), ('ml', 'ML/Data'), ('blockchain', 'Blockchain/Web3'), ('cloud', 'Cloud/DevOps'), ('concepts', 'Concepts')], default='languages', max_length=30),
        ),
    ]
