# Generated by Django 4.2.26 on 2025-12-01 11:44

from django.db import migrations, models
import portfolio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_video',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_app/videos', validators=[portfolio_app.models.Project.validator_video], verbose_name='Project Video'),
        ),
    ]
