# Generated by Django 4.2.26 on 2025-12-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_remove_project_project_profile_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Languages'), ('frameworks', 'Frameworks/Libraries'), ('frontend', 'Frontend Technologies'), ('backend', 'backend Technologies'), ('databases', 'Databases'), ('ml/ds', 'ML/Data Science'), ('cloud', 'Cloud/DevOps'), ('tools', 'Tools')], default='languages', max_length=30),
        ),
    ]
