# Generated by Django 4.2.26 on 2025-12-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=10, verbose_name='Certification Name')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compony_name', models.CharField(max_length=100, verbose_name='Compony Name')),
                ('compony_des', models.TextField(verbose_name='Description')),
                ('duration', models.CharField(verbose_name='Duration')),
                ('certificate_link', models.URLField(blank=True, null=True, verbose_name='Certificate Link')),
            ],
        ),
    ]
