# Generated by Django 4.2.26 on 2025-12-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_certificate_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_name',
            field=models.CharField(max_length=30, verbose_name='Certification Name'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Duration'),
        ),
    ]
